package testerGuiOwnerEngine

import "FenixGuiExecutionServer/common_config"

// Process the actual command 'ChannelCommand_UserSubscribesToUserAndTestCaseExecutionCombination'
func commandUserSubscribesToUserAndTestCaseExecutionCombination(
	guiExecutionServerIsClosingDown *common_config.GuiExecutionServerIsClosingDownStruct) {

}
