package testerGuiOwnerEngine

import "FenixGuiExecutionServer/common_config"

// Process the actual command 'ChannelCommand_AnotherGuiExecutionServerTakesThisUserAndTestCaseExecutionCombination'
func commandAnotherGuiExecutionServerTakesThisUserAndTestCaseExecutionCombination(
	guiExecutionServerIsClosingDown *common_config.GuiExecutionServerIsClosingDownStruct) {

}
