package testerGuiOwnerEngine

import "FenixGuiExecutionServer/common_config"

// Process the actual command 'ChannelCommand_ThisGuiExecutionServerTakesThisUserAndTestCaseExecutionCombination'
func commandThisGuiExecutionServerTakesThisUserAndTestCaseExecutionCombination(
	guiExecutionServerIsClosingDown *common_config.GuiExecutionServerIsClosingDownStruct) {

}
